In [1]:
import keras

Using TensorFlow backend.
/Users/dafirebanks/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/dafirebanks/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/dafirebanks/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/dafirebanks/anaconda3/lib/pytho

In [22]:
import pandas as pd
import numpy as np
import os

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import sgd

In [116]:
path = "../DataSetCover3001-4000/"

# from here: https://www.bogotobogo.com/python/python_traversing_directory_tree_recursively_os_walk.php
file_paths = []
for root, d_names, f_names in os.walk(path):
    for f in f_names:
        if f != ".DS_Store":
            file_paths.append(os.path.join(root, f))

In [7]:
test_input = np.loadtxt("Instance3001.csv", delimiter=",", dtype=int)

In [117]:
# remove labels and costs
file_paths.remove('../DataSetCover3001-4000/labels.csv')
file_paths.remove('../DataSetCover3001-4000/costs.csv')

In [14]:
x = test_input.flatten()
x.shape

(19584,)

In [107]:
all_data = []
for fp in file_paths:
    array = np.loadtxt(fp, delimiter=',', dtype=int).flatten()
    all_data.append(array)

TypeError: expected string or bytes-like object

In [32]:
all_lengths = [data.shape[0] for data in all_data]

In [61]:
limit = max(all_lengths)
limit

38313

In [38]:
td = all_data[0]

In [51]:
expansion = np.negative(np.ones((limit-td.shape[0],), dtype=int))

In [55]:
td.shape, expansion.shape

((7719,), (30594,))

In [60]:
np.concatenate((td, expansion)).shape

(38313,)

In [62]:
final_data = []
for data in all_data:
    expansion = np.negative(np.ones((limit-data.shape[0],), dtype=int))
    final = np.concatenate((data, expansion))
    final_data.append(final)

In [63]:
final_lengths = [data.shape[0] for data in final_data]
set(final_lengths)

In [64]:
set(final_lengths)

{38313}

In [147]:
from keras.models import Sequential

In [212]:
model = Sequential()
model.add(Dense(1000, activation='relu', input_shape=(1,)))
model.add(Dense(450, activation='sigmoid'))
model.add(Dense(250, activation='relu'))
model.add(Dense(1, activation='softmax'))

model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_51 (Dense)             (None, 1000)              2000      
_________________________________________________________________
dense_52 (Dense)             (None, 450)               450450    
_________________________________________________________________
dense_53 (Dense)             (None, 250)               112750    
_________________________________________________________________
dense_54 (Dense)             (None, 1)                 251       
Total params: 565,451
Trainable params: 565,451
Non-trainable params: 0
_________________________________________________________________


In [213]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [214]:
model.fit(X_train, y_train, epochs=50, batch_size=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50


ValueError: setting an array element with a sequence.

In [205]:
X_train

array([array([ 1,  0,  1, ..., -1, -1, -1]),
       array([ 1,  0,  0, ..., -1, -1, -1]),
       array([ 1,  0,  0, ..., -1, -1, -1]),
       array([ 0,  3,  4, ..., -1, -1, -1]),
       array([ 0,  0,  0, ..., -1, -1, -1]),
       array([ 0,  1,  0, ..., -1, -1, -1]),
       array([ 0,  9,  0, ..., -1, -1, -1]),
       array([ 0,  0,  0, ..., -1, -1, -1]),
       array([ 1,  1,  0, ..., -1, -1, -1]),
       array([ 0,  0,  6, ..., -1, -1, -1]),
       array([ 0,  1,  0, ..., -1, -1, -1]),
       array([ 0,  1,  2, ..., -1, -1, -1]),
       array([ 2,  0,  0, ..., -1, -1, -1]),
       array([ 0,  1,  1, ..., -1, -1, -1]),
       array([ 0,  0,  1, ..., -1, -1, -1]),
       array([ 1,  0,  0, ..., -1, -1, -1]),
       array([ 4,  6,  6, ..., -1, -1, -1]),
       array([ 0,  4,  4, ..., -1, -1, -1]),
       array([ 0,  2,  0, ..., -1, -1, -1]),
       array([ 0,  1,  2, ..., -1, -1, -1]),
       array([ 0,  1,  0, ..., -1, -1, -1]),
       array([ 0,  2,  0, ..., -1, -1, -1]),
       arr

In [65]:
'''
TODO:
1. Map labels to instances (Create method)
2. Feed them into network
3. '''

In [73]:
labels = pd.read_csv("../DataSetCover3001-4000/labels.csv")

In [75]:
labels.head()

Instance3001.csv   0
0  Instance3002.csv   3
1  Instance3003.csv   1
2  Instance3004.csv   0
3  Instance3005.csv   0
4  Instance3006.csv   3

In [99]:
labels = labels.rename(columns={' 0':'labels'})

In [100]:
labels.head()

Dataset  labels
0  Instance3002.csv       3
1  Instance3003.csv       1
2  Instance3004.csv       0
3  Instance3005.csv       0
4  Instance3006.csv       3

In [118]:
file_paths.sort()
file_paths = list(zip(file_paths[1:], labels['labels']))

In [119]:
file_paths

[('../DataSetCover3001-4000/Instance3002.csv', 3),
 ('../DataSetCover3001-4000/Instance3003.csv', 1),
 ('../DataSetCover3001-4000/Instance3004.csv', 0),
 ('../DataSetCover3001-4000/Instance3005.csv', 0),
 ('../DataSetCover3001-4000/Instance3006.csv', 3),
 ('../DataSetCover3001-4000/Instance3007.csv', 3),
 ('../DataSetCover3001-4000/Instance3008.csv', 1),
 ('../DataSetCover3001-4000/Instance3009.csv', 0),
 ('../DataSetCover3001-4000/Instance3010.csv', 0),
 ('../DataSetCover3001-4000/Instance3011.csv', 0),
 ('../DataSetCover3001-4000/Instance3012.csv', 0),
 ('../DataSetCover3001-4000/Instance3013.csv', 0),
 ('../DataSetCover3001-4000/Instance3014.csv', 0),
 ('../DataSetCover3001-4000/Instance3015.csv', 0),
 ('../DataSetCover3001-4000/Instance3016.csv', 0),
 ('../DataSetCover3001-4000/Instance3017.csv', 0),
 ('../DataSetCover3001-4000/Instance3018.csv', 0),
 ('../DataSetCover3001-4000/Instance3019.csv', 0),
 ('../DataSetCover3001-4000/Instance3020.csv', 0),
 ('../DataSetCover3001-4000/Ins

In [123]:
def get_all_data():
    all_data = []
    
    for fp in file_paths:
        array = np.loadtxt(fp[0], delimiter=',', dtype=int).flatten()
        all_data.append((array, fp[1]))
        
    final_data = []
    for data, label in all_data:
        expansion = np.negative(np.ones((limit-data.shape[0],), dtype=int))
        final = np.concatenate((data, expansion))
        final_data.append((final, label))
        
    return final_data

In [126]:
dset = np.array(get_all_data())

In [127]:
from sklearn.model_selection import train_test_split

In [129]:
dset.shape

(999, 2)

In [132]:
X = dset[:, 0]
y = dset[:, 1]

In [197]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=69420)

In [146]:
final_lengths = [data[0].shape[0] for data in dset]
set(final_lengths)

{38313}

In [155]:
len(X_train[2]

38313

In [193]:
X_train.shape

(899, 1, 38313)

In [192]:
y_train.shape

(899,)